source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’
use_frameworks!

target 'WeiMaiSwift' do
    pod 'Alamofire', '~> 4.4.0'
    pod 'SwiftyJSON', '~> 3.1.4'
    pod 'Kingfisher', '~> 3.10.1'
end
